name = "skills-market-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[routes]]
pattern = "api.skills.market/*"
zone_name = "skills.market"

[[d1_databases]]
binding = "DB"
database_name = "skills-market"
database_id = "9ea1dce0-a4fb-4458-b41d-a830bddfdf9d"

[dev]
port = 8787
local_protocol = "http"
